config/routes.rb
Rails.application.routes.draw do
  root "users#home"

  resources :users do
    resources :pirates do
      resources :ships do
        resources :ports
      end
      resources :houses
    end
  end
  resources :sessions, only: [:new, :create, :destroy]


  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  put "users/:user_id/pirates/:pirate_id/ships/:id/onboard", to: "pirates#onboard", as: "onboard"
  put "users/:user_id/pirates/:pirate_id/unboard", to: "pirates#unboard", as: "unboard"
  put "users/:user_id/pirates/:pirate_id/ships/:ship_id/port/:id/dock", to: "ships#dock", as: "dock"
  put "users/:user_id/pirates/:pirate_id/ship/:id/undock", to: "ships#undock", as: "undock"

  post "users/:user_id/pirates/:pirate_id/houses/:id", to: "pirates#buy_house", as: "buy_house"
  post "users/:user_id/pirates/:id/plunder", to: "pirates#plunder", as: "plunder"
end

app/models/port.rb
class Port < ApplicationRecord
  has_many :ships, dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController

  def index
    @ports = Port.all
    @ships = Ship.all
    @ship = Ship.find(params[:ship_id])
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])
  end

  def show
    @port = Port.find(params[:id])
    @ships = Ship.all
    @ship = Ship.find(params[:ship_id])
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])
  end

  def new
    @port = Port.new
  end

  def create
    @port = Port.new(port_params)
    @ports = Port.all
    @ships = Ship.all
    @pirates = Pirate.all
    @ship = Ship.find(params[:ship_id])
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])

    if @port.save
      render :index
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @pirate = Pirate.find(params[:pirate_id])
    @ship = Ship.find(params[:ship_id])
    @port = Port.find(params[:id])
    @port.destroy
    redirect_to user_pirate_ship_ports_path
  end

  private
  def port_params
    params.require(:port).permit(:name, :docks)
  end
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/ports/_form.html.erb
<%= form_with url: user_pirate_ship_ports_path, model: port do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% port.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :docks %><br>
    <%= form.select :docks, [2, 3, 4, 5], selected: 2 %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/ports/index.html.erb
<%= render "users/login" %>

<h2>Choose port you would like to dock in</h2>

<ul>
  <% @ports.each do |port| %>
    <li>
      <strong><%= link_to 'Port ' + port.name, user_pirate_ship_port_path(@user, @pirate, @ship, port) %></strong>
      occupied:
      <%= @ships.select { |s| s.port_id == port.id }.count %>
      / <%= port.docks %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'Add more ports', new_user_pirate_ship_port_path %></p>
<p><%= link_to 'Back', user_pirate_ship_path(@user, @pirate, @ship) %></p>

app/views/ports/new.html.erb
<%= render "users/login" %>

<h1>New Port</h1>

<%= render "form", port: @port %>

app/views/ports/show.html.erb
<%= render "users/login" %>

<h1><%= "Port " + @port.name %></h1>

<p>
  <strong>Docks:</strong>
  <%= @port.docks %>
</p>

<p>
  <strong>Vacant places:</strong>
  <%= @port.docks - @ships.select { |s| s.port_id == @port.id }.count %>
</p>

<p>
  <% if @ship.port_id == nil %>

    <% if (@ships.select { |s| s.port_id == @port.id }.count) < @port.docks %>
      <%= link_to "Dock ship!",dock_url(@user, @pirate, @ship, @port), method: :put %>
    <% else %>
      This port has all docks occupied.
    <% end %>

    <% else if @ship.port_id == @port.id %>
      <%= link_to "We sail to the sea!",undock_url(@user, @pirate, @ship), method: :put %>
    <% end %>
  <% end %>
</p>

<p>
  <%= link_to "Let's destroy this place!",
              user_pirate_ship_port_path(@user, @pirate, @ship, @port),
              method: :delete,
              data: { confirm: "You have your cannons with ya?" } %>
</p>

<p>
  <%= link_to "Back", user_pirate_ship_ports_path(@user, @pirate, @ship) %>
</p>