config/routes.rb
Rails.application.routes.draw do
  root "users#home"

  resources :users do
    resources :pirates do
      resources :ships do
        resources :ports
      end
      resources :houses
    end
  end
  resources :sessions, only: [:new, :create, :destroy]


  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  put "users/:user_id/pirates/:pirate_id/ships/:id/onboard", to: "pirates#onboard", as: "onboard"
  put "users/:user_id/pirates/:pirate_id/unboard", to: "pirates#unboard", as: "unboard"
  put "users/:user_id/pirates/:pirate_id/ships/:ship_id/port/:id/dock", to: "ships#dock", as: "dock"
  put "users/:user_id/pirates/:pirate_id/ship/:id/undock", to: "ships#undock", as: "undock"

  post "users/:user_id/pirates/:pirate_id/houses/:id", to: "pirates#buy_house", as: "buy_house"
  post "users/:user_id/pirates/:id/plunder", to: "pirates#plunder", as: "plunder"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :pirates, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def home
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @pirates = @user.pirates
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "User was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_login.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  Logged in as <%= current_user.name %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>

app/views/users/edit.html.erb
<%= render "login" %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<%= render "login" %>

<h1>Welcome to Pilates of the Calibbean!</h1>

<strong>Log in, create a pirate and become the greatest pirate in the world!</strong>

<div>
  <h3>How to play:</h3>
  <p>
    Register now, log in, create a pirate (or pirates) and take them for a ride!
    With your pirates, you can board ships, buy houses and visit ports.
  </p>
  <p>
    Your pirate starts as a mere commoner, with no gold and no prestige. You need to find a ship, board it and plunder
    as you wish! By plundering, you earn gold. Lots of gold! With that, you can buy houses. And by buying luxurious
    houses you gain prestige (depends on a value of the house - more expensive houses give you more prestige. The more
    expensive houses you buy, the more powerful your pirate becomes.
  </p>
  <p>
    But be careful! Other pirates can sink your ship and you become a commoner again, which means you cannot plunder
    no more. If you need more ships or ports to make, you are free to create them.
  </p>
  <p>
    Are you ready for a ride? Go and become the most powerful pirate in the world!
  </p>
</div>

app/views/users/index.html.erb
<%= render "login" %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render "login" %>

<h1>
  Name: <%= @user.name %>
</h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Delete', user_path(@user),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>

<h2>Your Pirates:</h2>
<ul>
  <% @pirates.each do |pirate| %>
    <li>
      <%= link_to pirate.name, user_pirate_path(@user, pirate) %>
    </li>
  <% end %>
</ul>

<h2>Create a new pirate:</h2>
<%= render 'pirates/form' %>