config/routes.rb
Rails.application.routes.draw do
  root "users#home"

  resources :users do
    resources :pirates do
      resources :ships do
        resources :ports
      end
      resources :houses
    end
  end
  resources :sessions, only: [:new, :create, :destroy]


  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  put "users/:user_id/pirates/:pirate_id/ships/:id/onboard", to: "pirates#onboard", as: "onboard"
  put "users/:user_id/pirates/:pirate_id/unboard", to: "pirates#unboard", as: "unboard"
  put "users/:user_id/pirates/:pirate_id/ships/:ship_id/port/:id/dock", to: "ships#dock", as: "dock"
  put "users/:user_id/pirates/:pirate_id/ship/:id/undock", to: "ships#undock", as: "undock"

  post "users/:user_id/pirates/:pirate_id/houses/:id", to: "pirates#buy_house", as: "buy_house"
  post "users/:user_id/pirates/:id/plunder", to: "pirates#plunder", as: "plunder"
end

app/models/pirate.rb
class Pirate < ApplicationRecord
  belongs_to :user
  belongs_to :ship, optional: true
  has_many :houses, dependent: :nullify

  validates :name, presence: true
end

app/controllers/pirates_controller.rb
class PiratesController < ApplicationController

  def show
    @pirate = Pirate.find(params[:id])
    @user = User.find(@pirate.user_id)
    @ships = Ship.all
    @houses = House.all
    if @pirate.ship_id != nil
      @ship = Ship.find(@pirate.ship_id)
    end
  end

  def create
    @user = User.find(params[:user_id])
    @pirate = @user.pirates.create(pirate_params)
    redirect_to user_path(@user)
  end

  def update
    @pirate = Pirate.find(params[:id])
  end

  def destroy
    @pirate = Pirate.find(params[:id])
    @user = User.find(@pirate.user_id)
    @pirate.destroy
    redirect_to user_url(@user)
  end

  def onboard
    @user = User.find(params[:user_id])
    @ship = Ship.find(params[:id])
    @pirate = Pirate.find(params[:pirate_id])
    @houses = House.where(:pirate_id => nil)
    @pirate.ship_id = @ship.id
    @pirate.status = "sailor"
    @pirate.save
    render :show
  end

  def unboard
    @user = User.find(params[:user_id])
    @houses = House.where(:pirate_id => nil)
    @pirate = Pirate.find(params[:pirate_id])
    @pirate.ship_id = nil
    @pirate.status = "commoner"
    @pirate.save
    render :show
  end

  def buy_house
    @pirate = Pirate.find(params[:pirate_id])
    @house = House.find(params[:id])
    if can_afford_to_buy?(@pirate, @house)
      buy(@pirate, @house)
      redirect_to user_pirate_houses_path, notice: "House bought successfully!"
    else
      redirect_to user_pirate_houses_path, notice: "Not enough gold!"
    end
  end

  def plunder
    @user = User.find(params[:user_id])
    @pirate = Pirate.find(params[:id])
    @pirate.gold += rand(5..15)*100
    @pirate.save
    redirect_to user_pirate_path, notice: "Plundering successful!"
  end

  private
  def pirate_params
    params.require(:pirate).permit(:name)
  end

  def can_afford_to_buy?(pirate, house)
    pirate.gold >= house.price
  end

  def buy(pirate, house)
    pirate.gold -= house.price
    pirate.prestige += house.prestige
    house.pirate_id = pirate.id
    pirate.save
    house.save
  end

end

app/helpers/pirates_helper.rb
module PiratesHelper
end

app/views/pirates/_form.html.erb
<%= form_with model: [ @user, @user.pirates.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pirates/show.html.erb
<%= render "users/login" %>

<h1><%= @pirate.name %></h1>

<p>
  <strong>Gold:</strong>
  <%= @pirate.gold %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pirate.status %>
</p>

<p>
  <strong>Prestige:</strong>
  <%= @pirate.prestige %>
</p>

<p>
  <strong>Ship:</strong>
  <% if @pirate.ship_id == nil %>
    This pirate is walking by foot.
  <strong><%= link_to 'Onboard!', user_pirate_ships_path(@user, @pirate) %></strong>
  <% else %>
    <%= link_to @ship.name, user_pirate_ship_path(@user, @pirate, @ship) %>
  <% end %>
</p>

<p>
  <strong>Houses:</strong>
  <%= @houses.select { |h| h.pirate_id == @pirate.id }.count %>
  <%= link_to "Buy houses", user_pirate_houses_path(@user, @pirate) %>
</p>

<% if @pirate.ship_id != nil %>
  <h3><%= link_to "Plunder! Hurray!", plunder_path(@user, @pirate), method: :post %></h3>
<% end %>

<p>
  <%= link_to "Delete", user_pirate_path(@user, @pirate),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
</p>


<p><%= link_to 'Back', user_path(@user) %></p>