config/routes.rb
Rails.application.routes.draw do
  root "users#home"

  resources :users do
    resources :pirates do
      resources :ships do
        resources :ports
      end
      resources :houses
    end
  end
  resources :sessions, only: [:new, :create, :destroy]


  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  put "users/:user_id/pirates/:pirate_id/ships/:id/onboard", to: "pirates#onboard", as: "onboard"
  put "users/:user_id/pirates/:pirate_id/unboard", to: "pirates#unboard", as: "unboard"
  put "users/:user_id/pirates/:pirate_id/ships/:ship_id/port/:id/dock", to: "ships#dock", as: "dock"
  put "users/:user_id/pirates/:pirate_id/ship/:id/undock", to: "ships#undock", as: "undock"

  post "users/:user_id/pirates/:pirate_id/houses/:id", to: "pirates#buy_house", as: "buy_house"
  post "users/:user_id/pirates/:id/plunder", to: "pirates#plunder", as: "plunder"
end

app/models/ship.rb
class Ship < ApplicationRecord
  has_many :pirates, dependent: :nullify
  belongs_to :port, optional: true

  validates :name, presence: true, uniqueness: true
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController

  def index
    @ships = Ship.all
    @pirates = Pirate.all
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])
  end

  def show
    @ship = Ship.find(params[:id])
    if @ship.port_id != nil
      @port = Port.find(@ship.port_id)
    end
    @pirates = Pirate.all
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])
  end

  def new
    @ship = Ship.new
  end

  def create
    @ship = Ship.new(ship_params)
    @ships = Ship.all
    @pirates = Pirate.all
    @pirate = Pirate.find(params[:pirate_id])
    @user = User.find(params[:user_id])

    if @ship.save
      render :index
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @pirate = Pirate.find(params[:pirate_id])
    @sailors = Pirate.where(:ship_id => params[:id])
    @sailors.each {|sailor|
      sailor.status = "commoner"
      sailor.save}
    @ship = Ship.find(params[:id])
    @ship.destroy
    redirect_to index
  end

  def dock
    @user = User.find(params[:user_id])
    @pirate = Pirate.find(params[:pirate_id])
    @pirates = Pirate.all
    @ship = Ship.find(params[:ship_id])
    @port = Port.find(params[:id])
    @ship.port_id = @port.id
    @ship.save
    render :show
  end

  def undock
    @user = User.find(params[:user_id])
    @pirate = Pirate.find(params[:pirate_id])
    @pirates = Pirate.all
    @ship = Ship.find(params[:id])
    @ship.port_id = nil
    @ship.save
    render :show
  end

  private
  def ship_params
    params.require(:ship).permit(:name, :capacity)
  end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.erb
<%= form_with url: user_pirate_ships_path, model: ship do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% ship.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :capacity %><br>
    <%= form.select :capacity, [10, 15, 20, 30], selected: 10 %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/ships/index.html.erb
<%= render "users/login" %>

<h2>What ship would you like to board?</h2>

<ul>
  <% @ships.each do |ship| %>
    <li>
      <strong><%= link_to ship.name, user_pirate_ship_path(@user, @pirate, ship) %></strong>
      occupied:
      <%= @pirates.select { |p| p.ship_id == ship.id }.count %>
      / <%= ship.capacity %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'Create a new ship', new_user_pirate_ship_path %></p>
<p><%= link_to 'Back', user_pirate_path(@user, @pirate) %></p>

app/views/ships/new.html.erb
<%= render "users/login" %>

<h1>New Ship</h1>

<%= render "form", ship: @ship %>

app/views/ships/show.html.erb
<%= render "users/login" %>

<h1><%= @ship.name %></h1>

<p>
  <strong>Capacity:</strong>
  <%= @ship.capacity %>
</p>

<p>
  <strong>Vacant places:</strong>
  <%= @ship.capacity - @pirates.select { |p| p.ship_id == @ship.id }.count %>
</p>

<p>
  <strong>Docked in:</strong>
  <% if @ship.port_id != nil %>
    <%= link_to "Port " + @port.name, user_pirate_ship_port_path(@user, @pirate, @ship, @port) %>
  <% else %>
    Ship is not docked
    <strong><%= link_to "Dock ship!", user_pirate_ship_ports_path(@user, @pirate, @ship) %></strong>
  <% end %>
</p>

<p>
  <% if @pirate.ship_id == nil %>

    <% if (@pirates.select { |p| p.ship_id == @ship.id }.count) < @ship.capacity %>
      <strong><%= link_to "Board!",onboard_url(@user, @pirate, @ship), method: :put %></strong>
     <% else %>
      This ship is already full.
    <% end %>

  <% else %>
    <%= link_to "Unboard!",unboard_url(@user, @pirate), method: :put %>
  <% end %>
</p>

<p>
<%= link_to "Sink dat ship! Yeah, it'sa good idea!",
            user_pirate_ship_path(@user, @pirate, @ship),
            method: :delete,
            data: { confirm: "You really wanna sink this ship?" } %>
</p>

<p>
  <%= link_to "Back", user_pirate_ships_path(@user, @pirate) %>
</p>